### ISSUE TITLE
Failed installation. Failed signature check

### ISSUE THREAD

**Issue by ipochto** [hissingshark/retrOSMCmk2#8]
Raspberry PI 3 
OSMC installed from "2020.06 Raspberry Pi 2 / 3 / 3+"-image from  https://osmc.tv
Then updated by `sudo apt-get dist-upgrade`

Run `RetroPie-Setup -> Basic install`
After several minutes off instalation process, have this message:

During installation failed signature check for:
`libsdl2-dev_2.0.10+5rpi_armhf.deb`
```
gpg: assuming signed data in 'libsdl2-dev_2.0.10+5rpi_armhf.deb'
gpg: Signature made Mon Sep 28 05:30:13 2020 CEST
gpg: using RSA key DC9D77FF8208FFC51D8F5)CCF1B030906A3B0D31
gpg: issuer "retropieproject@gmail.com"
gpg: Can't check signature: No public key
```

The same for `retroarch.tar.gz`

**Comment by hissingshark** [comment]
I'm looking at some RPi issues now. I take it you're still on Stretch?
Can you paste the entire log of that install to https://paste.osmc.tv/ and I'll see how it compares with my tests.

**Comment by ipochto** [comment]
>I take it you're still on Stretch?
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch
```

I just mentioned note about Stretch based distribution which setup script is shows. But, I have last image from osmc.tv and it's Stretch based. Is it safe for OSMC to manualy switch to the Buster? [upd: according to this: https://discourse.osmc.tv/t/osmc-update-to-buster/81364/26 they still not support Buster]

Requested log: 
https://paste.osmc.tv/vojoyujiya.coffee
*It's for the last try (second or third)

**Comment by hissingshark** [comment]
You don't need to be on Buster, but many people are testing it at this time, so I didn't want to assume.

**Comment by hissingshark** [comment]
@ipochto 
OK, I've found the bug with the signing keys.
I'll let you know when I've corrected it.

**Comment by ipochto** [comment]
Glad to hear it. Thanks you.
It was realy fast ))

**Comment by hissingshark** [comment]
That looks to be fixed, although I'll need to add some refinements in due course.

From the installer run:
`Manage retrOSMCmk2 -> Update retrOSMCmk2`
then:
`Manage RetroPie-Setup -> Re-install RetroPie-Setup`

Please report back how that works out.

**Comment by ipochto** [comment]
This issue is fixed. Thanks.

**Comment by richiec86** [comment]
I'm still getting this issue with public keys on the rpi4, on a fresh OSMC install with the update commands included.

Any suggestions?
